version: '3.3'

services:
  postgres:
    image: postgres:9.6
    command: -p 5433
    ports:
      - '127.0.0.1:5433:5433'

  web:
    build: .
    ports:
      - '0.0.0.0:8080:5000'
    volumes:
      - .:/code
    depends_on:
      - postgres
    restart: always
